"""Persistence ports used by the application-service layer.

The interfaces deliberately expose domain-shaped values and no SQL concepts. A
SQLite/PostgreSQL adapter can implement the same unit-of-work boundary later.
"""

from __future__ import annotations

from types import TracebackType
from typing import Protocol, Self
from uuid import UUID

from app.models.domain import (
    AnalysisJob,
    Criterion,
    CriterionProposal,
    CriterionProposalReviewRecord,
    CriterionValidation,
    Document,
    Project,
    Report,
    UserDecision,
)


class ProjectRepository(Protocol):
    async def get(self, project_id: UUID) -> Project | None: ...
    async def owner(self, project_id: UUID) -> str | None: ...
    async def add(self, project: Project, owner: str) -> None: ...
    async def list_for_owner(self, owner: str) -> list[Project]: ...


class DocumentRepository(Protocol):
    async def get(self, document_id: UUID) -> Document | None: ...
    async def add(self, document: Document) -> None: ...
    async def list_for_project(self, project_id: UUID) -> list[Document]: ...
    async def find_by_sha256(self, project_id: UUID, sha256: str) -> Document | None: ...


class CriterionRepository(Protocol):
    async def get(self, criterion_id: UUID) -> Criterion | None: ...
    async def add(self, criterion: Criterion) -> None: ...
    async def list_for_project(self, project_id: UUID) -> list[Criterion]: ...
    async def code_exists(self, project_id: UUID, normalized_code: str) -> bool: ...
    async def active_snapshot(self, project_id: UUID) -> tuple[int, list[Criterion]]: ...


class ReportRepository(Protocol):
    async def get(self, report_id: UUID) -> Report | None: ...
    async def add(self, report: Report) -> None: ...
    async def update(self, report: Report) -> None: ...
    async def list_for_project(self, project_id: UUID) -> list[Report]: ...
    async def external_identity_exists(
        self, project_id: UUID, external_system: str, external_id: str
    ) -> bool: ...


class AnalysisJobRepository(Protocol):
    async def get(self, job_id: UUID) -> AnalysisJob | None: ...
    async def add(self, job: AnalysisJob) -> None: ...
    async def update(self, job: AnalysisJob) -> None: ...
    async def set_criteria_snapshot(self, job_id: UUID, criteria: list[Criterion]) -> None: ...
    async def get_criteria_snapshot(self, job_id: UUID) -> list[Criterion]: ...


class CriterionProposalRepository(Protocol):
    async def get(self, proposal_id: UUID) -> CriterionProposal | None: ...
    async def add_many(self, proposals: list[CriterionProposal]) -> None: ...
    async def list_for_job(self, job_id: UUID) -> list[CriterionProposal]: ...
    async def get_review(self, proposal_id: UUID) -> CriterionProposalReviewRecord | None: ...
    async def add_review(self, review: CriterionProposalReviewRecord) -> None: ...


class ValidationRepository(Protocol):
    async def get(self, validation_id: UUID) -> CriterionValidation | None: ...
    async def add_many(self, validations: list[CriterionValidation]) -> None: ...
    async def list_for_report(self, report_id: UUID) -> list[CriterionValidation]: ...
    async def get_decision(self, validation_id: UUID) -> UserDecision | None: ...
    async def add_decision(self, decision: UserDecision) -> None: ...


class UnitOfWork(Protocol):
    projects: ProjectRepository
    documents: DocumentRepository
    criteria: CriterionRepository
    reports: ReportRepository
    jobs: AnalysisJobRepository
    proposals: CriterionProposalRepository
    validations: ValidationRepository

    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    async def commit(self) -> None: ...


class UnitOfWorkFactory(Protocol):
    def __call__(self) -> UnitOfWork: ...
